version: '3.1'

services:
<<<<<<< HEAD
  app:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 80:8000
=======
  checking:
    build: ./
    volumes:
      - static_volume:/home/www/staticfiles
    env_file:
      - .env
    expose:
      - 8000
    restart: always
>>>>>>> 9c8018ec3861ad5844d5bb2da562b67dff4c510f
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgresDb:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/www/staticfiles
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - checking

volumes:
  postgresDb:
  static_volume:
