version: '3.1'

services:
  checking:
    build: ./
    volumes:
      - static_volume:/home/www/staticfiles
    env_file:
      - .env
    expose:
      - 8000
    restart: always
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgresDb:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/www/staticfiles
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - checking

volumes:
  postgresDb:
  static_volume:
