version: '3.7'

services:
  app:
    build: ./
    command: bash -c "python manage.py collectstatic --no-input --clear && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 80:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgresDb:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
volumes:
  postgresDb:
