# Generated by Django 3.2.9 on 2023-05-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='name_of_specialty',
            field=models.CharField(max_length=400, unique=True, verbose_name='Наименование специальности'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='slug',
            field=models.SlugField(blank=True, max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='company_name',
            field=models.CharField(max_length=355, verbose_name='Наименовании компании'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='title',
            field=models.CharField(max_length=600, verbose_name='Заголовок вакансии'),
        ),
    ]
