# Generated by Django 3.2.9 on 2021-11-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20211127_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Url',
        ),
    ]
