# Generated by Django 3.2.9 on 2021-12-03 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_delete_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancies',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='General_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.city', verbose_name='Город')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.speciality', verbose_name='Специальность')),
            ],
            options={
                'unique_together': {('city', 'speciality')},
            },
        ),
    ]
