# Generated by Django 3.2.9 on 2021-12-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_auto_20211203_1922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='General_info',
        ),
    ]
