# Generated by Django 3.2.9 on 2022-02-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_delete_general_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='created_at',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
