# Generated by Django 3.2.9 on 2022-02-18 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_alter_vacancies_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название города'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='speciality',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.speciality', verbose_name='Специальность'),
        ),
    ]
