# Generated by Django 3.2.9 on 2022-02-18 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0008_auto_20220218_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='city',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.city', verbose_name='Город'),
        ),
    ]
