# Generated by Django 3.2.9 on 2022-02-18 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_regform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regform',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='regform',
            name='name_and_surname',
        ),
        migrations.RemoveField(
            model_name='regform',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='regform',
            name='user_name',
        ),
    ]
