# Generated by Django 3.2.9 on 2022-02-18 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0009_alter_vacancies_city'),
        ('accounts', '0003_auto_20220218_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraping.city'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraping.speciality'),
        ),
    ]
